spring:
  profiles:
    active: prod
  servlet:
    # 파일 크기 제한
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
    # redis 포트 설정
  redis:
    host: localhost
    port: 6379
  #    database 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
    jpa:
      hibernate:
        ddl-auto: create
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect