spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    # 파일 크기 제한
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
    # redis 포트 설정
  redis:
    host: localhost
    port: 6379
  #    database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_database?serverTimezone=Asia/Seoul&
    username: root
    password: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true



